<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.5">
  <POU Name="MAIN" Id="{98ae381b-1fae-4503-a3b8-1900850a68a0}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>